### ISSUE TITLE
Update to f string

### ISSUE THREAD

**Issue by JavascriptLearner815** [zaneanderman/disbot#1]
The code works, but the strings can be replaced with f strings.

What are f strings?

F strings are the best way to include variables in strings in Python.

For example:

`message = message+"id: "+str(person)+", "+"server name: "+person.display_name+"\n"`

can be:

`message = f"{message}id: {str(person)}", f"server name: {person.display_name}\n"`

instead.

**Comment by JavascriptLearner815** [comment]
The example above is not a complete conversion, as I don't really understand what the comma and extra stuff mean.

**Comment by zaneanderman** [comment]
> The example above is not a complete conversion, as I don't really understand what the comma and extra stuff mean.

The comma is in quotes, it doesn't mean anything special
